# Generated by Django 4.1.2 on 2022-10-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_posicion', models.CharField(choices=[('DT', 'Director Técnico'), ('PO', 'Portero'), ('DFC', 'Central'), ('LD', 'Lateral Derecho'), ('LI', 'Lateral Izquierdo'), ('MD', 'Medio Derecho'), ('MI', 'Medio Izquierdo'), ('MC', 'Medio Centro'), ('DC', 'Delantero Centro'), ('ED', 'Extremo Derecho'), ('EI', 'Extremo Izquierdo'), ('MCO', 'Medio Centro Ofensivo')], default='PO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('dorsal', models.IntegerField()),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_register.posicion')),
            ],
        ),
    ]
