# Generated by Django 4.1.2 on 2022-10-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0002_alter_posicion_tipo_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='posicion',
            field=models.CharField(choices=[('DT', 'Director Técnico'), ('PO', 'Portero'), ('DFC', 'Central'), ('LD', 'Lateral Derecho'), ('LI', 'Lateral Izquierdo'), ('MD', 'Medio Derecho'), ('MI', 'Medio Izquierdo'), ('MC', 'Medio Centro'), ('DC', 'Delantero Centro'), ('ED', 'Extremo Derecho'), ('EI', 'Extremo Izquierdo'), ('MCO', 'Medio Centro Ofensivo')], default='PO', max_length=40),
        ),
        migrations.DeleteModel(
            name='Posicion',
        ),
    ]
