# Generated by Django 4.1.2 on 2022-10-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0003_alter_miembro_posicion_delete_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='dorsal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
